#!/bin/bash
if [ -z "$1" ];then
    echo "ERR: must specify host"
    exit 1
fi
ssh "$1" mkdir -p work/timesync
scp Makefile timesync.c "$1:work/timesync"
ssh "$1" "(cd work/timesync; make clean all)"
ssh "$1" "(cd work/timesync; doas date '202510061338.01';doas ./timesync -v 192.168.1.1;sleep 1;date)"
