#!/bin/bash
if [ -z "$1" ];then
    echo "ERR: must specify host"
    exit 1
fi
ssh "$1" mkdir -p work/timesync
scp Makefile timesync.c "$1:work/timesync"
ssh "$1" "(cd work/timesync; make clean all; [ -f timesync ] && sudo cp timesync /usr/local/bin;ls -al /usr/local/bin/timesync)"
